### PR TITLE
reload button

### PR DESCRIPTION
**Pull request by felias-fogg**
This patch adds a reload button. It will reload the ELF symbol file, and flashes the program memory. Unfortunately, it does not update the function and classes panes yet. So, it is not perfect, but a start. So, I guess, more work has to be done here.

BTW: GDB even crashes when there is a breakpoint at a line which is not there anymore after a file has been changed. Maybe, one should exclude this modification anyway (or make it safer).

### CODE REVIEW

**Comment by jhn98032** [comment]
Lets see if I understand it correctly. You have gede opened and you have modifed your application. You compile your application and now you want to debug it again. This means closing gede and then open it again. Is the purpose of this patch that you do not want to close gede but instead just press a button that basically does everything that is done by closing and opening gede and by that saving some time? 

I like the idea! 

But would it not be better to totally close gdb and restart it with the new application? In other words close and cleanup everything and then call Core::initRemote()/Core::initLocal()/.... In that way we do not have to redo the initialization steps in a Core::gdbReload() function but instead let Core::initX() do it. So basically something like:

int Core::gdbReload()
{
    close();
    switch(whichModeAreWeIn())
    case REMOTE:  initRemote();break;
    case LOCAL: initLocal()
    
    .....
}

**Comment by felias-fogg** [comment]
Yes, of course. Restarting Gede would do the job. However, in my case, this takes 10-20 seconds, maybe more. So, a "soft" restart by loading the recompiled executable is preferable. And you may be right that restarting GDB is the right thing. However, restarting GDB will also take some time and GDB seems already be prepared to work with reloading binaries ("load") and restarting after that. The only necessary thing seems to be to update the function and class panes.

But you are probably the expert on what is the right thing to do. 

In any case, one should watch out for (re-)setting breakpoints on lines that do not exist anymore because GDB does not like that and might crash.

**Comment by felias-fogg** [comment]
I thought about it a bit longer. Terminating GDB and then restarting it is not preferable for several reasons. First, the network connection to the gdbserver will be terminated and needs to be re-established, which my server is not able to do yet. Then, the connection to the target has to be opened up again, which, in my case, means changing again into debugWIRE mode. All that will cost a few seconds, which would be good to avoid.

**Comment by felias-fogg** [comment]
As it stands, the PR is incomplete. And it is probably not worth the trouble. So, I close the PR.

**Comment by jhn98032** [comment]
@felias-fogg   See e0e0f81328b788e4c29fd2ef83e8121c97fcd5ae.

Instead of a dedicated "download" button Gede will ask the user if he wants to reload the program when he presses the "restart" button IF the program has been modified since the last run.
For network mode it will try to reuse the connection and for the other modes it will close and reopen gdb session.

In this way it will solve problem of having to close and start gede only because the program has changed. It will also solve your problem of having to wait for gdb to startup. There are however probably a lot of corner cases  that will not work but it is a start.

**Pull request closed without merging**
